# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='key',
            field=models.CharField(max_length=200, verbose_name='key'),
        ),
    ]
