# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import scraper.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20160615_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyserver',
            name='protocol',
            field=models.CharField(choices=[(b'http', b'HTTP'), (b'https', b'HTTPS')], max_length=16, validators=[scraper.validators.ChoicesValidator(((b'http', b'HTTP'), (b'https', b'HTTPS')))], verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='selector',
            name='data_type',
            field=models.CharField(choices=[(b'text', b'Text content'), (b'html', b'HTML content'), (b'binary', b'Binary content')], max_length=64, validators=[scraper.validators.ChoicesValidator(((b'text', b'Text content'), (b'html', b'HTML content'), (b'binary', b'Binary content')))]),
        ),
        migrations.AlterField(
            model_name='spider',
            name='mode',
            field=models.CharField(choices=[(b'crawl', 'crawl & scrape data'), (b'extract', 'extract from single page'), (b'read', 'get readable content')], default=b'crawl', max_length=32, validators=[scraper.validators.ChoicesValidator(((b'crawl', 'crawl & scrape data'), (b'extract', 'extract from single page'), (b'read', 'get readable content')))]),
        ),
    ]
